# Generated by Django 4.2.13 on 2024-07-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('FUNDING', 'Funding'), ('COMPENSATION', 'Compensation')], max_length=64)),
                ('source', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('photo1', models.ImageField(upload_to='uploadsArea/')),
                ('photo2', models.ImageField(upload_to='uploadsArea/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('PROMO', 'Promo'), ('0.5 гр.', '0.5 гр.'), ('1 гр.', '1 гр.'), ('2 гр.', '2 гр.'), ('3 гр.', '3 гр.'), ('4 гр.', '4 гр.'), ('5 гр.', '5 гр.'), ('10 гр.', '10 гр.'), ('20 гр.', '20 гр.')], default='0.5 гр.', max_length=256, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('type', models.CharField(choices=[('PreOrder', 'Pre Order'), ('Moment', 'Moment')], default='Moment', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('photo1', models.ImageField(upload_to='uploadsProduct/')),
                ('photo2', models.ImageField(upload_to='uploadsProduct/')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('city', models.ManyToManyField(blank=True, null=True, to='webhook.city')),
            ],
        ),
        migrations.CreateModel(
            name='PreOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.city')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.pack')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.product')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('tgId', models.IntegerField()),
                ('tgLogin', models.CharField(max_length=1024)),
                ('role', models.CharField(choices=[('DEFAULT', 'Default'), ('COURIER', 'Courirer'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='DEFAULT', max_length=64)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.shop')),
            ],
        ),
        migrations.AddField(
            model_name='pack',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.product'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Wait', 'Wait')], default='Wait', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.city')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.product')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='webhook.city'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=2048)),
                ('status', models.CharField(choices=[('OnSale', 'On Sale'), ('Sold', 'Sold')], default='OnSale', max_length=64)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_addresses', to='webhook.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_addresses', to='webhook.city')),
                ('fromPartner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.partner')),
            ],
        ),
    ]
