# Generated by Django 4.2.13 on 2024-07-11 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_alter_address_area_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook.shop'),
        ),
    ]
