# Generated by Django 4.2.13 on 2024-07-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_telegrambot_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='type',
            field=models.CharField(choices=[('ShopBot', 'ShopBot'), ('CourierBot', 'CourierBot')], default='CourierBot', max_length=64),
        ),
    ]
