# Generated by Django 4.2.13 on 2024-07-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_telegrambot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pack',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='webhook.pack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='webhook.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.city'),
        ),
    ]
