# Generated by Django 4.2.13 on 2024-07-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_address_pack_product_shop_alter_area_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BTC', 'BTC'), ('LTC', 'LTC')], max_length=64)),
                ('publicKey', models.CharField(max_length=1024)),
                ('privateKey', models.CharField(max_length=1024)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.partner')),
            ],
        ),
    ]
