# Generated by Django 4.2.13 on 2024-07-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0006_partner_balance_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='type',
        ),
        migrations.AddField(
            model_name='pack',
            name='preorder',
            field=models.BooleanField(default=False),
        ),
    ]
