# Generated by Django 4.2.13 on 2024-07-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0007_remove_pack_type_pack_preorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorderinfo',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webhook.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='pack',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webhook.pack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preorderinfo',
            name='partner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webhook.partner'),
            preserve_default=False,
        ),
    ]
