# Generated by Django 4.2.13 on 2024-07-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0008_remove_preorderinfo_product_order_address_order_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderinfo',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webhook.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preorderinfo',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webhook.shop'),
            preserve_default=False,
        ),
    ]
