# Generated by Django 4.2.13 on 2024-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0009_preorderinfo_order_preorderinfo_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fileId',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
