# Generated by Django 4.2.13 on 2024-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0010_address_fileid_address_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='fileId',
        ),
        migrations.AddField(
            model_name='address',
            name='file',
            field=models.ImageField(default=1, upload_to='uploadsAddresses/'),
            preserve_default=False,
        ),
    ]
