# Generated by Django 4.2.13 on 2024-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0011_remove_address_fileid_address_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='data',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='file',
            field=models.ImageField(null=True, upload_to='uploadsAddresses/'),
        ),
    ]
